### PR TITLE
Expose user helpers into evaluatorOptions

### PR DESCRIPTION
**Pull request by sembrestels**
In this way, we can define custom helper functions. Example:

```js
const radspec = require('../../src')
const web3 = require('web3-utils')

const expression = '`@toUtf8(gretting)` world.'
const bindings = {
  gretting: {
    type: 'bytes',
    value: '0x48656c6c6f'
  }
}
const options = {
  userHelpers: {
    toUtf8: () => async (hex) => {
      return {
        type: 'string',
        value: web3.toUtf8(hex)
      }
    }
  }
}

radspec.evaluateRaw(expression, bindings, options)
  .then(console.log) // => "Hello world."
  .catch(console.error)
```

### CODE REVIEW

**Comment by sembrestels** [comment]
Build is failing because of this issue: https://github.com/ethereum/web3.js/issues/1914. It is solved by updating NPM packages.

**Comment by izqui** [comment]
Amazing, thanks for the contribution!

**Comment by sembrestels** [comment]
The commit f020a299301e9051721b4af5bd25933e90fe4fac already exposes userHelpers, so I rebased the example and tests I wrote, just in case you want to use them.

**Comment by sohkai** [comment]
Thanks @sembrestels! We went in a different direction afterwards with #55 and this ended up making the original changes here unnecessary.

Of course, we still really appreciate the tests and extra examples ❤️ !

**Pull request merged**
