### PR TITLE
FIX #18 add power operator, example:  should be 2000

### LINKED ISSUE #18: Add power operator (^)
Instead of having to write 10^18 manually (10 with 18 zeroes), it would be nice if we could just write 10^18.

**Acceptance criteria**
- Power operator using the hat character (`^`)
- Tests that demonstrate that the operator works as intended (include at least one that demonstrates its associativity)

### PR DESCRIPTION
**Pull request by oivoodoo**
Hi guys.

Fixed the issue for testing purporse of open bounty program.

I hope it looks ok.

FIX #18

### CODE REVIEW

**Comment by onbjerg** [comment]
This is not exactly right. 2^2 is 4 (2 * 2), and 2^5 is 32 (2 * 2 * 2 * 2 * 2). Can you fix the tests to reflect this, and also add a test case that demonstrates that it works correctly in more complex situations, such as (11 - 1) * 2^5 which should be 320?

**Comment by oivoodoo** [comment]
@onbjerg working on it. sorry for that. submitted to see how ci works. locally it's producing the issues to master branch at all for me.

**Comment by onbjerg** [comment]
@oivoodoo No worries! Feel free to submit WIP pull requests, that's fine 😊

**Comment by oivoodoo** [comment]
@onbjerg could you check the build error here https://travis-ci.org/aragon/radspec/jobs/328128826 ? I have the build error locally. probably you could help me to resolve it

**Comment by oivoodoo** [comment]
@onbjerg don't worry. I know what it's about the issue

**Comment by oivoodoo** [comment]
@onbjerg it should be ok now! 💯

**Comment by onbjerg** [comment]
We will pay out the bounty today, but please be a bit patient since the network is having a hard time right now.

Also, double check that you have set your payment address on openbounty.status.im 😊

**Comment by oivoodoo** [comment]
Hi @onbjerg . this fix is for test transfer by using openbounty program because I lost my huge previous transfer because of weird issues that I can't resolve for now :)

**Comment by onbjerg** [comment]
@oivoodoo Have you tried reaching out to Status? They're usually pretty responsive when it comes to Open Bounties.

**Comment by oivoodoo** [comment]
@onbjerg yes, everything is in progress. don't know how but probably I had old eth address from metamask(changed laptop and forgot to make backup of metamask) attached to openbounty account :) now I definitely has the right address there.

**Pull request merged**
