### PR TITLE
Use ES6 import and export syntax

### LINKED ISSUE #46: Migrate library to using new ES6 import / export syntax
After moving to babel, we've gotten bit by not using the ES6 module syntax (see [fix for `date-fns`](https://github.com/aragon/radspec/pull/45)).

The rest of the library should also be moved over for consistency and to avoid any future issues.

### PR DESCRIPTION
**Pull request by sembrestels**
Fixes #46.

### CODE REVIEW

**Comment by sembrestels** [comment]
@sohkai I just amended my commit to follow standard style rules and replaced a last require I forget the first time.

**Comment by sembrestels** [comment]
Rebased on top of master.

**Comment by sohkai** [comment]
Thanks for doing this @sembrestels, this was really nice!

I've just added a commit to keep the `wallaby.js` as CJS, since I'm not sure if Wallaby supports loading config files through ES6 and another to fix a test and clean up the import/export declarations a bit :).

**Comment by sembrestels** [comment]
Awesome! Thanks!

**Pull request merged**
